spring:
  application:
    name: autorizador

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password: password
  flyway:
    enabled: true
  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080
